apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-host
spec:
  accessModes:
    # - ReadWriteOnce
    - ReadWriteMany #여러 클라이언트를 위한 읽기 쓰기 마운트
  capacity:
    storage: 1Gi
  hostPath:
    # path: /tmp/Users/yoonsikbyun/Documents/minikube_mnt
    path: /Users/yoonsikbyun/Documents/minikube_mnt