apiVersion: v1 
kind: PersistentVolumeClaim
metadata: 
  name: pvc-host
spec: 
  storageClassName: ""
  accessModes: 
    # - ReadWriteOnce
    - ReadWriteMany #여러 클라이언트를 위한 읽기 쓰기 마운트
  resources: 
    requests: 
      storage: 1Gi
