apiVersion: v1 
kind: PersistentVolumeClaim
metadata: 
  name: pvc-host-nfs
  namespace: storage
spec: 
  storageClassName: ""
  accessModes: 
    - ReadWriteOnce
  resources: 
    requests: 
      storage: 1Gi