apiVersion: v1
kind: Pod
metadata:
  name: ''
  labels:
    tier: airflow
    component: worker
    release: mlstudio
spec:
  containers:
    - name: ''
      image: ''
      imagePullPolicy: IfNotPresent
      workingDir: /opt/mlstudio/source
      args: []
      command: []
      resources: {}
