apiVersion: v1
kind: ConfigMap
metadata:
  name: mlstudio-config
  labels:
    tier: mlstudio-config
    component: config
data:
  # These are system-specified config overrides.
  mlstudio-confog.json: |-
    {
      system-database : {
        ip : '10.10.10.10',
        port : 1000
      }
    }

  mlstudio-confog2.json: |-
    {
      system-database : {
        ip : '10.10.10.10',
        port : 1000
      }
    }
