apiVersion: v1
kind: ConfigMap
metadata:
  name: sftp-server-config
  labels:
    app : sftp-server

data:
  sftp.json: |-
    {
        "Global": {
            "Chroot": {
                "Directory": "%h",
                "StartPath": "sftp"
            },
            "Directories": ["sftp"]
        },
        "Users": [
            {
                "Username": "mlflow-artifacts",
                "Password": "mlflow-artifacts"
            }
        ]
    }

---
# Source: sftp/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sftp-server
  labels:
    helm.sh/chart: sftp-5.1.69
    app.kubernetes.io/name: sftp
    app.kubernetes.io/instance: sftp-server
    app.kubernetes.io/version: "5.1.69"
    app.kubernetes.io/managed-by: Helm
---
apiVersion: v1
kind: Service
metadata:
  name: sftp-server-nodeport
  namespace: default
spec:
  type: NodePort
  selector:
    app: sftp-server
  ports:
    -
      name: sftp-server
      port: 22
      nodePort: 30022
---
# Source: sftp/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: sftp-server
  labels:
    helm.sh/chart: sftp-5.1.69
    app.kubernetes.io/name: sftp
    app.kubernetes.io/instance: sftp-server
    app.kubernetes.io/version: "5.1.69"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 22
      targetPort: ssh
      protocol: TCP
      name: ssh
  selector:
    app.kubernetes.io/name: sftp
    app.kubernetes.io/instance: sftp-server
---
# Source: sftp/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sftp-server
  labels:
    helm.sh/chart: sftp-5.1.69
    app.kubernetes.io/name: sftp
    app.kubernetes.io/instance: sftp-server
    app.kubernetes.io/version: "5.1.69"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: sftp
      app.kubernetes.io/instance: sftp-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sftp
        app.kubernetes.io/instance: sftp-server
    spec:
      serviceAccountName: sftp-server
      securityContext:
        {}
      containers:
        - name: sftp
          securityContext:
            {}
          image: "emberstack/sftp:5.1.69"
          imagePullPolicy: Always
          ports:
            - name: ssh
              containerPort: 22
              protocol: TCP    
          livenessProbe:
            tcpSocket:
              port: ssh
          readinessProbe:
            tcpSocket:
              port: ssh
          resources:
            {}
          volumeMounts:
            - name: sftp-server-config
              mountPath: "/app/config/sftp.json"
              subPath: sftp.json
              readOnly: false
            - name: host-mount
              mountPath: "/home/mlflow-artifacts/sftp"
              subPath: mlflow/mlruns
              readOnly: false
      volumes:
        - name: sftp-server-config
          configMap:
            name: sftp-server-config
        - name: host-mount
          persistentVolumeClaim:
            claimName: pvc-host