# This image provides a Python 3.11 environment you can use to run your Python
# applications.
FROM mlstudio/python3.11:latest

ARG USERNAME=mlstudio

USER $USERNAME

RUN pip3 install --no-cache-dir matplotlib numpy pandas plotly scikit-learn scipy statsmodels xgboost lightgbm Flask gunicorn \
         jupyterlab jupyterlab-git nbdime lckr_jupyterlab_variableinspector

ENV PATH="${PATH}:/home/$USERNAME/.local/bin:"

