apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity: #용량
    storage: 1Gi # PersistentVolume(PV) 사이즈를 지정한다.
  accessModes:
    - ReadWriteMany #여러 클라이언트를 위한 읽기 쓰기 마운트
  nfs:
    server: 10.1.3.28 # nfs서버의 ip주소
    path: /exports #nfs서버에서 공유한 디렉토리명
