apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc ##PVC의 이름으로 나중에 pod의 볼륨을 요청할 때 사용한다
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany #ReadWriteMany(RWX) : 여러 개의 노드가 마운트 가능
  resources:
    requests:
      storage: 1Gi #1 GiB의 스토리지를 요청한다.